export const callType = {
  CHAT_PERSONAL_CODE: "CHAT_PERSONAL_CODE",
  CHAT_STRANGER: "CHAT_STRANGER",
  VIDEO_PERSONAL_CODE: "VIDEO_PERSONAL_CODE",
  VIDEO_STRANGERL_CODE: "VIDEO_STRANGERL_CODE",
};
